/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.validation

import com.google.inject.Inject
import org.eclipse.xtext.example.calculation.KnapsackCalculator
import org.eclipse.xtext.example.knapsack.KnapsackPackage
import org.eclipse.xtext.example.knapsack.KnapsackProblem
import org.eclipse.xtext.validation.Check
import org.eclipse.xtext.validation.ValidationMessageAcceptor

class KnapsackValidator extends AbstractKnapsackValidator {
	@Inject extension KnapsackCalculator

    @Check
    def checkCompilation(KnapsackProblem it) {
    	val expected = calculateOptimum
    	val actual = packedItem
    	
        if (expected.size != actual.size || !(0..actual.size-1).exists(index|expected.get(index) == actual.get(index))) {
            warning(
            	"Current compilation is not the optimum", 
            	KnapsackPackage$Literals::KNAPSACK_PROBLEM__CAPACITY,
            	ValidationMessageAcceptor::INSIGNIFICANT_INDEX,
            	IssueCodes::WRONG_COMPILATION
            );
        }
    }

}
