/*
* generated by Xtext
*/
package org.eclipse.xtext.example.knapsack;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class KnapsackStandaloneSetup extends KnapsackStandaloneSetupGenerated{

	public static void doSetup() {
		new KnapsackStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

