/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.knapsack;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KnapsackRuntimeModule extends org.eclipse.xtext.example.knapsack.AbstractKnapsackRuntimeModule {

}
