/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.knapsack.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class KnapsackUiModule extends org.eclipse.xtext.example.knapsack.ui.AbstractKnapsackUiModule {
	public KnapsackUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
