/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.knapsack.ui.contentassist

import org.eclipse.xtext.example.knapsack.ui.contentassist.AbstractKnapsackProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class KnapsackProposalProvider extends AbstractKnapsackProposalProvider {
}
